from application.core.exceptions.base import CustomException


class YourBaseException(CustomException):
    pass
